### ISSUE TITLE
Missing toString / hashCode / equals methods for Overlay Types

### ISSUE THREAD

**Issue by belowm** [konsoletyper/teavm#328] opened 2018-02-15 08:37 UTC
It seems as if Overlay Types have no implementation of the methods inherited from java.lang.Object:

```
abstract class Window implements JSObject {
	@JSBody( script = "return window;" )
	static native Window create();
}
```

```
public static void main( final String[] args ) {
	final Window window = Window.create();
	System.out.println( window );
}
```
gives:
```
runtime.js:545 Uncaught TypeError: $obj.$toString is not a function
    at jl_AbstractStringBuilder_insert3 (classes.js:1060)
    at jl_StringBuilder_insert (classes.js:1223)
    at jl_StringBuilder.$insert4 (classes.js:2380)
    at jl_StringBuilder_insert3 (classes.js:1250)
    at jl_StringBuilder.$insert3 (classes.js:2382)
    at jl_AbstractStringBuilder_append4 (classes.js:1057)
    at jl_StringBuilder_append3 (classes.js:1219)
    at jl_StringBuilder.$append (classes.js:2380)
    at ji_PrintStream_println (classes.js:655)
    at ji_PrintStream.$println (classes.js:2362)
```

This happens even when toString is overwritten on the Window class.

Tested with the current master branch.

**Comment by konsoletyper** [comment] 2018-02-15 08:47
Right, they aren't meant to have implementation of java.lang.Object methods. The correct behaviour for TeaVM is to warn about attempt to call these methods.

**Comment by konsoletyper** [comment] 2018-02-15 08:50
Currently, this warning is not implemented.

**Comment by belowm** [comment] 2018-02-15 09:10
Hm, I think having java objects without these methods feels rather odd. E.g., they cannot be put into HashMap / HashSet, and one has to be very careful not cause errors at runtime.  Also, I don't think it will be possibly to always know at compile time if such a method is ever invoked. Wouldn't it make sense to generate default implementations of these method?

**Comment by konsoletyper** [comment] 2018-02-15 09:21
It's possible to catch these invocation at compile time. Yes, they can't be put into HashMap/HashSet, but you can write Java wrapper that can be actually put there.

These methods can't be generated, since overlay objects are not real Java object, it's just a tricky way to express JavaScript APIs using Java type system. You can explore generated JavaScript code and see that TeaVM does not create wrapper classes for JavaScript objects.

**Comment by teras** [comment] 2018-06-07 12:03
I think I'd agree with @belowm 
Under java, missing these methods feels odd.
I spent 1.5 days trying to find out why my code didn't work, just because I was using as "debug" strategy to println objects to check for null.
After many hours of work I found out that the problem was println itself.

I understand that maybe someone needs to change his habits when coding in teavm, but, if I may suggest, please be these changes as seldom and innocent as possible.

**Comment by konsoletyper** [comment] 2018-06-07 13:12
@teras I don't implement these methods not because I'd like to make things as non-obvious as possible. I just see no way of implementing these methods without performance penalty, not just in interop, but in the whole TeaVM. If you have an idea, feel free to share it.

**Comment by teras** [comment] 2018-06-07 14:10
If I understand correctly, the problem is that javascript does not provide per se an optimum hashing function. 
toString is trivial upon that.

So, here is the question:  if hashCode is indeed required, any impkementation (even the worst), would be better than nothing. Of course hashing would not be as trivial as with Java (where jsut the memory address is given), but even if it is calculated with a higher level function, it would be there.

I performed a random google search and found a couple of hashing implementations in JS, I don't think it's important to list them here (although I could).

**Comment by konsoletyper** [comment] 2018-06-07 14:21
> If I understand correctly, the problem is that javascript does not provide per se an optimum hashing function.

@teras implementing hashing function is not a problem. The problem is that existing JavaScript objects *do not* provide `equals`/`hashCode`/`toString`/`getClass` methods. How do I add them? Sure, I could add them to the `Object` prototype, but such monkey patching leads to huge problems and in modern JavaScript is considered a bad practice. TeaVM strongly follows principle: do not spoil any objects. So I can do nothing.

Again, hashing function is not a problem, that's why `java.lang.Object` and all Java classes have `hashCode` implemented.

> toString is trivial upon that.

No, it's not trivial. In JavaScript toString returns JavaScript string, while Java string in TeaVM *is not represented as JavaScript string*, due to many reasons. Since JavaScript objects do not know anything about TeaVM, it's still very challenging.

> Of course hashing would not be as trivial as with Java (where just the memory address is given)

Wrong. HotSpot does not use memory address, since memory address of an object can change.

**Comment by teras** [comment] 2018-06-07 15:53
@konsoletyper I think I understand you logic and don't take it wrong: I find your project amazing and I see it from a newbie/clean mind perspective.

I am not proficient with JS of course, that's why I am trying to use this project. Moreover I consider myself quite proficient in Java related issues. So excuse my ignorance on JS when I am trying to help.

From my point of view, and as it seems it is not only mine, TeaVM *should* be a Java alternative for the web, so the inconsitencies of JS should be kept aside and focus on how the Java expirience should be optimized. If you don't agree with this, then practically there's no other reason to use TeaVM, if JS idioms are more important, then everything should be kept in JS and everybody would be happy.

But I don't believe this is the case here. TeaVM has the potential to even bypass the restrictions of GWT and create a superior ecosystem. But this would succeed only if things in Java are as the people who write Java expect them to be - not how people who write JS. TeaVM should be Java for the Web, not JavaScript with Java syntax (as GWT is).

So, to comment on your position:

> @teras implementing hashing function is not a problem. The problem is that existing JavaScript objects do not provide equals/hashCode/toString/getClass methods. How do I add them? Sure, I could add them to the Object prototype, but such monkey patching leads to huge problems and in modern JavaScript is considered a bad practice.

Maybe, but I don't even **need** to imagine the huge problems I'd have with missing toString/equals etc. I have **experienced** it - for 1 1/2 days.

The main advantage over GWT this project has is that it works on top of bytecode - thus any random off the shelf java library (is supposed to) work with TeaVM. And all those libraries always expect these methods to exist.
So yes, I agree with you, it might be a disaster to "monkey patch" everything, (or maybe only JSObject?), but it would be an even **bigger** disaster to miss vital parts of the language itself. 

>  TeaVM strongly follows principle: do not spoil any objects.

Couldn't agree more.

 > So I can do nothing.

Couldn't agree less.


> No, it's not trivial. In JavaScript toString returns JavaScript string, while Java string in TeaVM is not represented as JavaScript string, due to many reasons. Since JavaScript objects do not know anything about TeaVM, it's still very challenging.

This even makes my point more powerfull. If the "toString" produces completely different and unexpected results in JavaVM and TeaVM, this would lead to countless debugging and testing and "scratching my head" times, although it could be easier avoided. Being challenging is another issue which is discussable.

> Wrong. HotSpot does not use memory address, since memory address of an object can change.

Here you are wrong. Not the physical RAM memory address, but the [internal memory address of the object](https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#hashCode--). By the definition:
> This is typically implemented by converting the internal address of the object into an integer, but this implementation technique is not required by the Java™ programming language.

To conclude, I write this with full faith on your project and its future, and I'd really love to make it even better. I am not trying to highjack your ideas or anything. In the contrary you have a big thank you from me and I hope you understand that I am trying, from my point of you, to make it even better.

**Comment by konsoletyper** [comment] 2018-06-07 18:15
@teras first of all, before we go on falling into abstract discussions. Is it correct that your pain point was the inability to detect the issue with hashCode/equals quckly? Was it better is compiler helped you to find the problem? Was it better if teavm.org provided detailed information how to work-around this problem? Is it so important to fix this problem by implementing hashCode/equals, or compiler diagnotic + documentation was enough?

> If you don't agree with this, then practically there's no other reason to use TeaVM, if JS idioms are more important, then everything should be kept in JS and everybody would be happy.

I didn't say I disagree. TeaVM tries to be as much JVM as possible, while also not violating JS code as much as possible. So if you stay entirely in Java, TeaVM will behave like Java.

> But this would succeed only if things in Java are as the people who write Java expect them to be - not how people who write JS

TeaVM **is** Java when you deal with Java. But remember, there's no such thing like 'JS interoperation layer' in Java, TeaVM had to invent its own API. And yes, when you interoperate between JS and Java, you have to think both in JS and Java. That's not only about TeaVM. If you write JNI code, you have to think both in Java and C++.

> TeaVM should be Java for the Web, not JavaScript with Java syntax (as GWT is).

That's not true both for TeaVM and GWT. Both try to be as much Java as possible. However, there *are* challenges being 100% in the browser, and you can't achieve this goal without getting huge JavaScript with poor performance. Both TeaVM and GWT choose practical approach introducing some trade-offs. Examples are:

* Dereferencing null pointer does not produce NullPointerException. Instead, it produces some native exception which is impossible to catch with usual Java try/catch.
* There's no array bounds checking; instead of getting AIOOBE, you get `null` result.
* There's no WeakReference.
* There's no reflection (not true in case of TeaVM; latest versions provide very limited support).

And yes, another example is inability to put JavaScript objects to Java containers. In server Java, you can't put C++ objects to HashSet as well.

BTW, WebAssembly backend would allow to overcome some of these limitations. Some of my recent commits improve WebAssembly support, but it's still far from being production-ready.

> thus any random off the shelf java library (is supposed to) work with TeaVM.

Unfortunately, this is not true. These libraries may use JDK parts that aren't still implemented in TeaVM or can't be implemented at all (like reflection or class loaders).

> And all those libraries always expect these methods to exist.

That's true for Java objects, but these libraries were not designed to work with JavaScript objects. These libaries can't handle C++ objects as well.

>> So I can do nothing.
> Couldn't agree less.

Ok, you can't agree, and I don't agree with you. IMO, it's useless to write "I disagree". What's your point? As I said, *I do nothing*, it's a fact. May be someone can, maybe no one can. For example, I can't play piano, how can you answer: "I disagree, you can't play piano". It's a nonsence.

> This even makes my point more powerfull. If the "toString" produces completely different and unexpected results in JavaVM and TeaVM

`toString` works in TeaVM *exactly* the same way as in JVM, *except* for the JavaScript objects. Unfortunately, Java was not designed for interoperation with JavaScript, and there is no second type hierarchy for this purpose. I would be glad if I could make a second type hierarchy rooted by `JSObject`, but I can't alter Java language and Java compiler this way. So `JSObject` inherits all `Object` methods, like 'equals', 'hashCode', but *actually* does not provide them.

> this would lead to countless debugging and testing and "scratching my head" times, although it could be easier avoided

It would lead to writing a quick workaroud for this corner case if TeaVM reported an error on the code that attempts to call Objects methods in JSObject.

> here you are wrong. Not the physical RAM memory address, but the internal memory address of the object. 

Documentation does not state anything. What is "internal memory address". What is "RAM address"? Of course, some JVM implementation which does not relocate objects (oh, it would be a poor one) could use memory address for this purpose. HotSpot [does not](https://srvaroa.github.io/jvm/java/openjdk/biased-locking/2017/01/30/hashCode.html).

**Comment by teras** [comment] 2018-06-07 18:40
Thank you again for the elaborated answer.

I'd agree that one of the main problems was the inability to catch this type of inconsistencies as early as possible. Although I do love the "single object tree approach", I won't insist any more, at least for now :smile: 

I don't know if it would be possible to catch them at compile time (i.e. I don't know what something like `System.out.prinltn("Window is " + Window.current());` could be caught early); though even a proper custom exception or whatever at run time would be really helpful.

Thank you again for your great magic you provide to us.

**Comment by Maxdamantus** [comment] 2023-09-07 09:21
> @teras I don't implement these methods not because I'd like to make things as non-obvious as possible. I just see no way of implementing these methods without performance penalty, not just in interop, but in the whole TeaVM. If you have an idea, feel free to share it.

Would it not be possible by just resolving unknown `Object.toString` calls to a static function that does an `instanceof` check, or is that considered too much of a performance penalty? Currently these seem to be compiled as `x.$toString()`, but if they were instead compiled as `$rt_toString(x)` (new runtime function), that function could call `x.$toString()` for Java objects (`x instanceof $java.jl_Object`) or `$rt_str(String(x))` for everything else (possibly also with a special case for `null`/`undefined`).

This would apply at most only for the 9 public methods on `Object`, and usually only when the static type is only known to be `Object`, since most types are statically known[0] to be a subtype of `JSObject` (emit `$rt_str(String(x))`) or not a subtype of `JSObject` (emit `x.$toString()`).

[0] If someone an overlay such as `public abstract class Foo implements JSObject, Runnable` exists, I think `Runnable` would have to be added to this set of static types that have both `JSObject` and non-`JSObject` subtypes.

**Closed** 2023-09-07 10:15 UTC
