### ISSUE TITLE
Missing String.split() ?

### ISSUE THREAD

**Issue by stevepugh99** [konsoletyper/teavm#98] opened 2015-04-18 16:05 UTC
I get the following error trying to compile:

Unexpected error occured: Can't compile due to the following items missing:
[ERROR] java.lang.String.split(Ljava/lang/String;)[Ljava/lang/String;

The line in question is
String[] chars = line.split(" ");

Is it possible to use String.split() ?

Also, is there a list of Java SDK classes/methods which are NOT supported, that we could refer to?

**Comment by shannah** [comment] 2015-04-18 16:21
Duplicate of https://github.com/konsoletyper/teavm/issues/82

**Comment by stevepugh99** [comment] 2015-04-18 16:42
Oh yes, so it is.
But there is javascript string.split method - would it not be possible to translate it direct to using that?

**Comment by konsoletyper** [comment] 2015-04-18 17:23
List of JDK classes available in TeaVM is available [here](http://teavm.org/jcl-support/0.2.x/jcl.html), as stated in project's site. You can build the latest version of TeaVM to use String.split. In this case you can find list of JDK classes in the `teavm-classlib/target/jcl-report/` subdirectory.

JavaScript regexps and Java regexps are different. In the recent version there is its own implementation of Java regexps ported from Apache Harmony. BWT, personally I rarely use regexps, since they are based on a slow backtracking algoritm.

**Closed** 2015-04-20 13:46 UTC
Labels: wontfix
